//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassManager_StudentCrack.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassManager_StudentCrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NetCinema_Img {
            get {
                object obj = ResourceManager.GetObject("NetCinema_Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 网络影院-教师可以在自己的计算机上播放媒体档案，并将播放的媒体文件广播至整个教室。+~+~全屏模式：若教师启用全屏，则学生无法退出全屏。+~窗口模式：学生可以自由调整窗口。 的本地化字符串。
        /// </summary>
        internal static string NetCinema_Str {
            get {
                return ResourceManager.GetString("NetCinema_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NetVideo_Img {
            get {
                object obj = ResourceManager.GetObject("NetVideo_Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 视频直播-教师直播自身USB摄像头的画面至多个学生。+~+~全屏模式：若教师启用全屏，则学生无法退出全屏。+~窗口模式：学生可以自由调整窗口。 的本地化字符串。
        /// </summary>
        internal static string NetVideo_Str {
            get {
                return ResourceManager.GetString("NetVideo_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ScreenShow_Img {
            get {
                object obj = ResourceManager.GetObject("ScreenShow_Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 屏幕广播-教师可以在全屏或窗口模式下广播教师端屏幕至学生端屏幕。+~+~全屏模式：若教师启用全屏，则学生无法退出全屏。+~窗口模式：学生可以自由调整窗口。 的本地化字符串。
        /// </summary>
        internal static string ScreenShow_Str {
            get {
                return ResourceManager.GetString("ScreenShow_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StdShow_Img {
            get {
                object obj = ResourceManager.GetObject("StdShow_Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 学生演示-教师选择一名学生向指定学生组转播画面。+~+~全屏模式：若教师启用全屏，则学生无法退出全屏。+~窗口模式：学生可以自由调整窗口。 的本地化字符串。
        /// </summary>
        internal static string StdShow_Str {
            get {
                return ResourceManager.GetString("StdShow_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap WhiteBoard_Img {
            get {
                object obj = ResourceManager.GetObject("WhiteBoard_Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 共享白板-教师通过将画布共享给学生的方式，邀请学生一起作画。共享白板功能提供了丰富多彩的绘制工具，帮助教师和学生进行共同创作。学生也可以进行独立绘制，教师可以监看每个学生的绘制画面，并选择学生将他的画面演示给其他学生。+~+~全屏模式：若教师启用全屏，则学生无法退出全屏。+~窗口模式：学生可以自由调整窗口。 的本地化字符串。
        /// </summary>
        internal static string WhiteBoard_Str {
            get {
                return ResourceManager.GetString("WhiteBoard_Str", resourceCulture);
            }
        }
    }
}
